# Generated by Django 5.0.7 on 2024-07-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_has_used_password_reset_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_used_password_reset_link',
        ),
    ]
