# Generated by Django 5.0.7 on 2024-10-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_watchlater'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlater',
        ),
    ]
