# Generated by Django 5.0.7 on 2024-11-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_watchlater_video_id_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10000000)),
                ('music', models.CharField(max_length=10000000)),
            ],
        ),
    ]
